value = input('Digite algo: ')
print(f'O tipo primitivo desse valor é {type(value)}')
print(f'Só tem espaços? {value.isspace()}')
print(f'É um número? {value.isnumeric()}')
print(f'É alfabético? {value.isalpha()}')
print(f'É alfanumérico? {value.isalnum()}')
print(f'Está em maiúsculas? {value.isupper()}')
print(f'Está em minúsculas? {value.islower()}')
print(f'Está capitalizada? {value.istitle()}')